### ISSUE TITLE
Generated link contains special characters

### ISSUE THREAD

**Issue by mkfelser** [klausj1/MarkdownLinkCompletionProvider#1]
Version: v0.0.2

Special characters do not get removed in link creation.
E.g. the header `Import/Export` will be converted to the link `#import/export` but should become `#importexport`.
Same with brackets e.g.: `APIs (SDKs)` 

update:
* adding colon `:` to the list of *tested* unwanted characters e.g. `Technology: abc`
* if removing of special characters results in multiple spaces, only one dash `-` should be used in the link e.g. `abc / xyz` --> `#abc-xyz`

**Comment by klausj1** [comment]
Solved, please retest.
If everything works, you should be able to install the extension via VSCode Marketplace now (https://marketplace.visualstudio.com/items?itemName=KlausJandl.markdownlinkcompletionprovider)

**Comment by mkfelser** [comment]
Most of my cases work now.
Only the mix of spaces and special characters does not always work in VSCode but you mentioned that in your current readme file.
